name: restaurantapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  flutter_native_splash: ^2.4.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  motion_tab_bar: ^2.0.4
  shared_preferences: ^2.0.13
  firebase_storage: ^12.1.0
  image_cropper: ^7.1.0
  image_picker: ^1.1.2
  intl: ^0.17.0
  google_sign_in: ^6.2.1
 



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


flutter_native_splash:
  color: "#ffffff"
  android: true
  ios: true
